### PR TITLE
chore: make smtp use optional

### PR DESCRIPTION
**Pull request by bastienriviereocd**
Create a new feature to enable or not smtp. This is useful for project that are not using it, but also, to disable openssl dependency.

Also remove async-native-tls since it was not used.

### CODE REVIEW

**Review by JuxhinDB — APPROVED** [review]
Thank you for this, appreciate the PR. Curious, can I ask what the project/use-case you are using twistrs for?

Also if you need this bumped on crates soon let me know and I'll publish it shortly.

**Comment by bastienriviereocd** [comment]
> Thank you for this, appreciate the PR. Curious, can I ask what the project/use-case you are using twistrs for?
> 
> Also if you need this bumped on crates soon let me know and I'll publish it shortly.

Sure, we are using it for generating a list of twisted domain and then pipe it in different tools.
We are trying to extract as much info of domain and their twisted variants.

I would appreciate the bump in version!

**Comment by JuxhinDB** [comment]
> I would appreciate the bump in version!

You can now pull `0.4.3` from [crates.io](https://crates.io/crates/twistrs).

That's great to hear, I do have some plans to overhaul parts of the library, particularly the error handling to use `anyhow`/`thiserror` which I'll release in a 0.5.x track. 

> Sure, we are using it for generating a list of twisted domain and then pipe it in different tools.
> We are trying to extract as much info of domain and their twisted variants.

I hope the permutations performed well, definitely open to adding more methods in there (mobile keyboard typos comes to mind). Final question: would a developer-friendly platform be something you would consider subscribing to achieve this functionality?

**Comment by bastienriviereocd** [comment]
> > I would appreciate the bump in version!
> 
> You can now pull `0.4.3` from [crates.io](https://crates.io/crates/twistrs).

Thanks!

> That's great to hear, I do have some plans to overhaul parts of the library, particularly the error handling to use `anyhow`/`thiserror` which I'll release in a 0.5.x track.

That would be great!

> > Sure, we are using it for generating a list of twisted domain and then pipe it in different tools.
> > We are trying to extract as much info of domain and their twisted variants.
> 
> I hope the permutations performed well, definitely open to adding more methods in there (mobile keyboard typos comes to mind). Final question: would a developer-friendly platform be something you would consider subscribing to achieve this functionality?

I would like to have more detail on this since I am not sure what you mean by this. Is it an API to twist and enrich domains?

**Comment by bastienriviereocd** [comment]
> Something similar to https://haveibeensquatted.com/ where you simply add your domains you'd like to monitor and automatically receive reports/alerts via email/slack/webhook/splunk etc. (inbound) or expose APIs to integrate with (outbound). Appreciate the follow-up comments by the way!

Well that's a great idea to commercialize this project, but unfortunately, we are making a product in this kind of category haha. But I think you could try to sell it to other companies easily.

**Pull request merged**
